version: '3.8'
services:
  sqlite-migrator:
    container_name: database
    build: ./db
    volumes:
      - db-data:/app/data

  email_sender_service:
    depends_on:
      - sqlite-migrator
      
    container_name: ess
    build: ./email_sender_service
    volumes:
      - db-data:/app/data
    environment:
      - ESS_PORT=$ESS_PORT
      - ESS_PASS=$ESS_PASS
      - ESS_EMAIL=$ESS_EMAIL
    env_file:
      - .env
    ports:
      - "$ESS_PORT:$ESS_PORT"

volumes:
  db-data: